[application]

# App (Project) Name
name = "site"

[web.app]

# HTML title tag content
title = "site"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
